version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_test
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - db:db
    networks:
      - delimanio

  db:
    image: postgres:11
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: delmanio
      POSTGRES_PASSWORD: delmanio123
      POSTGRES_DB: delmanio_db
    networks:
      - delimanio

volumes:
  db-data:

networks:
  delimanio:
    driver: bridge